<a href="https://colab.research.google.com/github/nag07799/my_pytorch_journey/blob/main/Pytorch_day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Setting random seed

import torch

RANDOM_SEED = 30
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)
print(random_tensor_C)

random_tensor_D = torch.rand(3, 4)
print(random_tensor_D)

tensor([[0.9007, 0.7464, 0.4716, 0.8738],
        [0.7403, 0.7840, 0.8946, 0.6238],
        [0.4276, 0.8421, 0.7454, 0.6181]])
tensor([[0.8883, 0.4127, 0.1748, 0.3426],
        [0.9377, 0.0413, 0.1127, 0.6972],
        [0.8760, 0.3163, 0.2989, 0.7827]])


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
### Checking Access of GPU
import torch
torch.cuda.is_available()

False

In [ ]:
#Seeting up
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
torch.cuda.device_count() #to get devices count

0

In [ ]:
#creating tensor
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
#Moving tensor to gpu if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

In [ ]:
### If the tensor is on GPU we can't change to numpy directly. We need to set first it to CPU

In [ ]:
### Moving tendot back to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
import torch
from torch import nn
import matplotlib.pyplot as plt

In [ ]:
### Torch Version
print(torch.__version__)

2.4.0+cu121


In [ ]:
weight = 0.7
bias = 0.3
X= torch.arange(0, 1, 0.02).unsqueeze(dim=1)
y = weight * X + bias

X[:10], y[:10]

(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260]]))

In [ ]:
from os import X_OK
#### Splitting Data into train and test

train_split = int(0.8 * len(X))
X_train, y_train = X[:train_split], y[:train_split]
X_test, y_test = X[train_split:], y[train_split:]
