<a href="https://colab.research.google.com/github/nag07799/my_pytorch_journey/blob/main/Pytorch_day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Setting random seed

import torch

RANDOM_SEED = 30
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)
print(random_tensor_C)

random_tensor_D = torch.rand(3, 4)
print(random_tensor_D)

tensor([[0.9007, 0.7464, 0.4716, 0.8738],
        [0.7403, 0.7840, 0.8946, 0.6238],
        [0.4276, 0.8421, 0.7454, 0.6181]])
tensor([[0.8883, 0.4127, 0.1748, 0.3426],
        [0.9377, 0.0413, 0.1127, 0.6972],
        [0.8760, 0.3163, 0.2989, 0.7827]])


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
### Checking Access of GPU
import torch
torch.cuda.is_available()

False

In [ ]:
#Seeting up
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
torch.cuda.device_count() #to get devices count

0

In [ ]:
#creating tensor
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
#Moving tensor to gpu if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

In [ ]:
### If the tensor is on GPU we can't change to numpy directly. We need to set first it to CPU

In [ ]:
### Moving tendot back to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
import torch
from torch import nn
import matplotlib.pyplot as plt

In [ ]:
### Torch Version
print(torch.__version__)

2.4.0+cu121


In [ ]:
weight = 0.7
bias = 0.3
X= torch.arange(0, 1, 0.02).unsqueeze(dim=1)
y = weight * X + bias

X[:10], y[:10]

(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260]]))

In [ ]:
from os import X_OK
#### Splitting Data into train and test

train_split = int(0.8 * len(X))
X_train, y_train = X[:train_split], y[:train_split]
X_test, y_test = X[train_split:], y[train_split:]

len(X_train), len(y_train), len(X_test), len(y_test)

(40, 40, 10, 10)

In [ ]:
import matplotlib.pyplot as plt


In [ ]:
  from torch import nn
### Creating Linear Regression

class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.weights = nn.Parameter(torch.randn(1, requires_grad=True, dtype=torch.float))
    self.bias = nn.Parameter(torch.randn(1, requires_grad=True, dtype=torch.float))

  #Forward computation
  def forward(self, x: torch.Tensor) -> torch.Tensor:
    return self.weights * x + self.bias



### Pytorch Model Building Essentials

## torch.nn - contains all of the buildings for computational graphs ( a neural network is also computational graph)
## torch.nn.parameters - parameters need to be mentioned that our model needs to try and learn
## torch.nn.Module : Base class for all nn modules, if you subclass it, you should overwriter forward
## torch.optim to choose for optimizer



In [ ]:
#Create a random seed to replicate results
torch.manual_seed(42)

#Create a model
model_0 = LinearRegressionModel()
list(model_0.parameters())

[Parameter containing:
 tensor([0.3367], requires_grad=True),
 Parameter containing:
 tensor([0.1288], requires_grad=True)]

In [ ]:
### Listing named parameters
model_0.state_dict()

OrderedDict([('weights', tensor([0.3367])), ('bias', tensor([0.1288]))])

### Inferencing Model

In [ ]:
## To check our model's prediction with torch.inference_mode
with torch.inference_mode():
  y_preds = model_0(X_test)
y_preds

tensor([[0.3982],
        [0.4049],
        [0.4116],
        [0.4184],
        [0.4251],
        [0.4318],
        [0.4386],
        [0.4453],
        [0.4520],
        [0.4588]])

In [ ]:
y_test

tensor([[0.8600],
        [0.8740],
        [0.8880],
        [0.9020],
        [0.9160],
        [0.9300],
        [0.9440],
        [0.9580],
        [0.9720],
        [0.9860]])