<a href="https://colab.research.google.com/github/nag07799/my_pytorch_journey/blob/main/Pytorch_day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
#Setting random seed

import torch

RANDOM_SEED = 30
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)
print(random_tensor_C)

random_tensor_D = torch.rand(3, 4)
print(random_tensor_D)

tensor([[0.9007, 0.7464, 0.4716, 0.8738],
        [0.7403, 0.7840, 0.8946, 0.6238],
        [0.4276, 0.8421, 0.7454, 0.6181]])
tensor([[0.8883, 0.4127, 0.1748, 0.3426],
        [0.9377, 0.0413, 0.1127, 0.6972],
        [0.8760, 0.3163, 0.2989, 0.7827]])


In [39]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [40]:
### Checking Access of GPU
import torch
torch.cuda.is_available()

False

In [41]:
#Seeting up
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [42]:
torch.cuda.device_count() #to get devices count

0

In [43]:
#creating tensor
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [44]:
#Moving tensor to gpu if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

In [45]:
### If the tensor is on GPU we can't change to numpy directly. We need to set first it to CPU

In [46]:
### Moving tendot back to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [47]:
import torch
from torch import nn
import matplotlib.pyplot as plt

In [48]:
### Torch Version
print(torch.__version__)

2.4.0+cu121


In [49]:
weight = 0.7
bias = 0.3
X= torch.arange(0, 1, 0.02).unsqueeze(dim=1)
y = weight * X + bias

X[:10], y[:10]

(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800]]),
 tensor([[0.3000],
         [0.3140],
         [0.3280],
         [0.3420],
         [0.3560],
         [0.3700],
         [0.3840],
         [0.3980],
         [0.4120],
         [0.4260]]))

In [50]:
from os import X_OK
#### Splitting Data into train and test

train_split = int(0.8 * len(X))
X_train, y_train = X[:train_split], y[:train_split]
X_test, y_test = X[train_split:], y[train_split:]

len(X_train), len(y_train), len(X_test), len(y_test)

(40, 40, 10, 10)

In [51]:
import matplotlib.pyplot as plt


In [52]:
from torch import nn
### Creating Linear Regression

class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.weights = nn.Parameter(torch.randn(1, requires_grad=True, dtype=torch.float))
    self.bias = nn.Parameter(torch.randn(1, requires_grad=True, dtype=torch.float))

  #Forward computation
  def forward(self, x: torch.Tensor) -> torch.Tensor:
    return self.weights * x + self.bias



### Pytorch Model Building Essentials

## torch.nn - contains all of the buildings for computational graphs ( a neural network is also computational graph)
## torch.nn.parameters - parameters need to be mentioned that our model needs to try and learn
## torch.nn.Module : Base class for all nn modules, if you subclass it, you should overwriter forward
## torch.optim to choose for optimizer



In [53]:
#Create a random seed to replicate results
torch.manual_seed(42)

#Create a model
model_0 = LinearRegressionModel()
list(model_0.parameters())

[Parameter containing:
 tensor([0.3367], requires_grad=True),
 Parameter containing:
 tensor([0.1288], requires_grad=True)]

In [54]:
### Listing named parameters
model_0.state_dict()

OrderedDict([('weights', tensor([0.3367])), ('bias', tensor([0.1288]))])

In [55]:
weight, bias

(0.7, 0.3)

### Inferencing Model

In [56]:
## To check our model's prediction with torch.inference_mode
with torch.inference_mode(): #It doesn't track gradients we can also use torch.no_grad, however inference mode is preferred compared to no_grad
  y_preds = model_0(X_test)
y_preds

tensor([[0.3982],
        [0.4049],
        [0.4116],
        [0.4184],
        [0.4251],
        [0.4318],
        [0.4386],
        [0.4453],
        [0.4520],
        [0.4588]])

In [57]:
y_test

tensor([[0.8600],
        [0.8740],
        [0.8880],
        [0.9020],
        [0.9160],
        [0.9300],
        [0.9440],
        [0.9580],
        [0.9720],
        [0.9860]])

## 3.Train model
### 1. Forward Pass
### 2. Caluculate the loss
### 3. Optimizer zero grad
### 4. Loss backward
### 5. Optimizer step


### 3.1 Going from raw logits -> prediction probabilities ->prediction labels

Our model outputs are goijng to be raw **logits**

In [58]:
model_0

LinearRegressionModel()

In [59]:
  model_0 = torch.nn.Sequential(
    torch.nn.Linear(in_features=1, out_features=1)
)

In [62]:
loss_fn = nn.L1Loss()
optimizer = torch.optim.SGD(params=model_0.parameters(), lr=0.01)

### training and Looping

In [61]:
torch.manual_seed(42)

## Setting number of epochs

#Building training and evaluation loop


In [ ]:
optimizer.zero_grad()

In [70]:
epochs=100000


## Training
#0. Loop throught the data
for epoch in range(epochs):
  model_0.train()  #it is in the train mode

  # Forward pass
  y_pred = model_0(X_train)

  #Calculate the loss
  loss = loss_fn(y_pred, y_train)

  #Optimizer
  optimizer.zero_grad()

  #Loss backward
  loss.backward()

  #Optimizer step
  optimizer.step() #by default how the optimizer  changes will accumulate through the loop

  #Testing
  # model_0.eval() #it is in the evaluation mode and turing off gradf




In [71]:
with torch.inference_mode():
  y_preds = model_0(X_test)

In [72]:
y_preds

tensor([[0.8542],
        [0.8681],
        [0.8820],
        [0.8959],
        [0.9097],
        [0.9236],
        [0.9375],
        [0.9514],
        [0.9653],
        [0.9792]])

In [4]:
!gunzip BooksAll.2016.part01.xml.gz


In [74]:
import xml.etree.ElementTree as ET

# Specify the path to the XML file
xml_file = 'BooksAll.2016.part01.xml'

# Parse the XML file
tree = ET.parse(xml_file)
root = tree.getroot()

# Access elements in the XML
# Example: Print the root tag and its attributes
print(f"Root tag: {root.tag}, Attributes: {root.attrib}")

# Example: Iterate through the elements
for child in root:
    print(f"Tag: {child.tag}, Attributes: {child.attrib}")

# If you know the structure of your XML, you can also access specific elements directly
# Example: Access all elements with a specific tag
for book in root.findall('book'):  # Replace 'book' with the appropriate tag in your XML
    title = book.find('title').text  # Replace 'title' with the appropriate child tag
    print(f"Book title: {title}")


Streaming output truncated to the last 5000 lines.
Tag: {http://www.loc.gov/MARC21/slim}record, Attributes: {}
Tag: {http://www.loc.gov/MARC21/slim}record, Attributes: {}
Tag: {http://www.loc.gov/MARC21/slim}record, Attributes: {}
Tag: {http://www.loc.gov/MARC21/slim}record, Attributes: {}
Tag: {http://www.loc.gov/MARC21/slim}record, Attributes: {}
Tag: {http://www.loc.gov/MARC21/slim}record, Attributes: {}
Tag: {http://www.loc.gov/MARC21/slim}record, Attributes: {}
Tag: {http://www.loc.gov/MARC21/slim}record, Attributes: {}
Tag: {http://www.loc.gov/MARC21/slim}record, Attributes: {}
Tag: {http://www.loc.gov/MARC21/slim}record, Attributes: {}
Tag: {http://www.loc.gov/MARC21/slim}record, Attributes: {}
Tag: {http://www.loc.gov/MARC21/slim}record, Attributes: {}
Tag: {http://www.loc.gov/MARC21/slim}record, Attributes: {}
Tag: {http://www.loc.gov/MARC21/slim}record, Attributes: {}
Tag: {http://www.loc.gov/MARC21/slim}record, Attributes: {}
Tag: {http://www.loc.gov/MARC21/slim}record, Attr

In [5]:
import xml.etree.ElementTree as ET

# Define the XML namespace
namespace = {'marc': 'http://www.loc.gov/MARC21/slim'}

# Load and parse the XML file
tree = ET.parse('BooksAll.2016.part01.xml')  # Replace with the correct file path
root = tree.getroot()

# Iterate through each record in the XML file
for record in root.findall('marc:record', namespace):
    # Extract control fields
    leader = record.find('marc:leader', namespace).text
    control_fields = record.findall('marc:controlfield', namespace)

    # Extract data fields
    data_fields = record.findall('marc:datafield', namespace)

    print(f"Leader: {leader}")

    # Print control fields
    for control_field in control_fields:
        tag = control_field.get('tag')
        value = control_field.text.strip()
        print(f"Control Field - Tag: {tag}, Value: {value}")

    # Print data fields
    for data_field in data_fields:
        tag = data_field.get('tag')
        ind1 = data_field.get('ind1')
        ind2 = data_field.get('ind2')
        subfields = data_field.findall('marc:subfield', namespace)
        subfield_data = {subfield.get('code'): subfield.text for subfield in subfields}
        print(f"Data Field - Tag: {tag}, Ind1: {ind1}, Ind2: {ind2}, Subfields: {subfield_data}")

    print("\n" + "-"*40 + "\n")


Streaming output truncated to the last 5000 lines.
Control Field - Tag: 001, Value: 00028963
Control Field - Tag: 003, Value: DLC
Control Field - Tag: 005, Value: 20001228071946.0
Control Field - Tag: 008, Value: 000308s2001    nyu           000 1 eng
Data Field - Tag: 010, Ind1:  , Ind2:  , Subfields: {'a': '   00028963 '}
Data Field - Tag: 020, Ind1:  , Ind2:  , Subfields: {'a': '0446527289'}
Data Field - Tag: 040, Ind1:  , Ind2:  , Subfields: {'a': 'DLC', 'c': 'DLC', 'd': 'DLC'}
Data Field - Tag: 043, Ind1:  , Ind2:  , Subfields: {'a': 'n-us-dc'}
Data Field - Tag: 050, Ind1: 0, Ind2: 0, Subfields: {'a': 'PS3563.E4496', 'b': 'F57 2001'}
Data Field - Tag: 082, Ind1: 0, Ind2: 0, Subfields: {'a': '813/.54', '2': '21'}
Data Field - Tag: 100, Ind1: 1, Ind2:  , Subfields: {'a': 'Meltzer, Brad.'}
Data Field - Tag: 245, Ind1: 1, Ind2: 4, Subfields: {'a': 'The first counsel /', 'c': 'Brad Meltzer.'}
Data Field - Tag: 260, Ind1:  , Ind2:  , Subfields: {'a': 'New York :', 'b': 'Warner Books,', 

KeyboardInterrupt: 