<a href="https://colab.research.google.com/github/nag07799/my_pytorch_journey/blob/main/Pytorch_day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install torch

  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinu

In [4]:
import torch

In [5]:
#1. Creating Random Tensor

random_tensor = torch.rand(size=(4,5))
print(random_tensor)


tensor([[0.9383, 0.3139, 0.2795, 0.6649, 0.3617],
        [0.8797, 0.8166, 0.2516, 0.6547, 0.3817],
        [0.6959, 0.5680, 0.4440, 0.2926, 0.2195],
        [0.0276, 0.3232, 0.6749, 0.0064, 0.1064]])


In [6]:
#2. Tensor of all zeros
zeros= torch.zeros(5,6)
print(zeros)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])


In [8]:
# 3. Creating Tensor of all one's
ones=torch.ones(4,6)
print(ones)
print(ones.dtype) # Data type defaul data type is torch.float32

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
torch.float32


In [16]:
#4. Creating a range of tensors with specified range
zero_to_ten = torch.arange(start=0,end= 11, step=1)
print(zero_to_ten)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [17]:
#5.Creating tensors like
ten_zeros=torch.zeros_like(input=zero_to_ten)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


In [24]:
### Tensor datatypes (defaut type is float 32)
float_16_tensor = torch.tensor([3.0,6.0,9.0],dtype=torch.float16)
print(float_16_tensor.dtype)

#three other  important parameters
#dtype= float 16,float32,float64
#device could be gpu if cuda
#requires_grad= True or False




torch.float16


In [25]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=torch.float32)
print(float_32_tensor.dtype)


torch.float32


In [30]:
### Getting information from Tensors
print(float_32_tensor.shape)#shape of the tensor
print(float_32_tensor.device)#device used cpu or gpu
print(float_32_tensor.dtype) # data type of the tensor
# print(float_32_tensor.size())

torch.Size([3])
cpu
torch.float32


In [32]:
###Manipulating Tensors

tensor =torch.tensor([1,2,3])
print(tensor+10) #Adding
torch.add(tensor,10) # Adding
print(tensor*10) # Multiplying
torch.mul(tensor,10) # Multiplying
print(tensor-10) #Subtracting
torch.sub(tensor,10) #Subtracting
print(tensor/10) # Division
torch.div(tensor,10) # Division

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])
tensor([0.1000, 0.2000, 0.3000])


tensor([0.1000, 0.2000, 0.3000])

In [33]:
### Matrix Multiplication
print(tensor*tensor) # element wise multiplication
print(torch.matmul(tensor,tensor)) # matrix multiplication or dot product

tensor([1, 4, 9])
tensor(14)


In [36]:
### Handling shape errors

# torch.matmul(torch.rand(3,2),torch.rand(3,3)) error
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.4721, 0.3034, 0.2311],
        [0.2340, 0.1879, 0.1103],
        [1.0327, 0.7638, 0.4942]])

In [41]:
### Finding max,min,sum,mean
print(tensor.max())
print(tensor.min())
print(tensor.sum())
print(torch.mean(tensor.type(torch.float32)))

tensor(3)
tensor(1)
tensor(6)
tensor(2.)


In [43]:
###max position
tensor.argmax()
###min position
torch.argmin(tensor)


tensor(0)

### Reshaping,stacking,squeezing,unsqueezing

*Reshaping - Reshapes an input tensor to a defined shape

*View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor

*Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)

*Squeeze - Remove all '1' dimensions from a tensor



In [50]:
import torch
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [49]:
# Add an extra dimension
x_reshaped=x.reshape(3,3,1)
x_reshaped,x_reshaped.shape

(tensor([[[1.],
          [2.],
          [3.]],
 
         [[4.],
          [5.],
          [6.]],
 
         [[7.],
          [8.],
          [9.]]]),
 torch.Size([3, 3, 1]))

In [51]:
z= x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [52]:
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [54]:
#Stack tensors on top of ech other
x_stacked=torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [58]:
#torch.squeeze
print(x.shape)
x=torch.reshape(x,(1,9))
print(x.shape)
squeezed=torch.squeeze(x)

torch.Size([1, 9])
torch.Size([1, 9])


In [64]:
unsqueezed = torch.unsqueeze(squeezed,dim=1)
print(unsqueezed)
print(unsqueezed.shape)

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
torch.Size([9, 1])


In [66]:
### Permute torch

x_original=torch.rand(size=(224,224,3))
x_original.shape

x_permuted=x_original.permute(2,0,1) #tensor.permute(dimension that you want to change)
x_permuted.shape

#if original tensor value is changed it reflects same in the permuted tensor as well

torch.Size([3, 224, 224])

In [69]:
### Indexing
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [70]:
# indexing on new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [71]:
x[0][0] #first row

tensor([1, 2, 3])

In [75]:
x[0][2] #first row

tensor([7, 8, 9])

In [72]:
x[0][0][0] #first element of the first row

tensor(1)

In [73]:
x[0][2][2] #last element of the last row

tensor(9)

In [77]:
x[:,:,-1] #all values of the middle column

tensor([[3, 6, 9]])

In [78]:
x[:,1,:]

tensor([[4, 5, 6]])

In [80]:
x[0,2,2] # to return last element
x[:,:,2]

tensor([[3, 6, 9]])

In [81]:
### torch to numpy
#numpy default is float64 be careful with that
import torch
import numpy as np
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [82]:
### Numpy to torch
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))